export default [{
	path: '/',
	name: '首页',
	title: '你拼图我送票'
}, {
	path: '/activity',
	name: '游戏页',
	title: '你拼图我送票'
}, {
	path: '/success/1/5',
	title: '闯关成功',
	name: '闯关成功'
}, {
	path: '/fail/1/3',
	title: '闯关失败',
	name: '闯关失败'
}, {
	path: '/rank',
	name: '总排行',
	title: '总排行'
}, {
	path: '/receive/:g/:n',
	name: '领取页',
	title: '领取'
}, {
	path: '/receive-success/:g',
	name: '领取结果页',
	title: '领取成功'
}, {
	path: '/prize',
	name: '我的奖品页',
	title: '我的奖品'
}]